#!/usr/bin/env python3
"""Build the Arouse agent corpus and the AgentBench case files.

    artifacts/datasets/<name>/train.jsonl     {"text": rendered episode}  (large, not committed)
    datasets/<name>/MANIFEST.json             provenance + sha256 (committed)
    <bench-dir>/test.jsonl                    held-out tasks/templates (committed)
    <bench-dir>/in_distribution.jsonl         train-distribution samples, unseen seeds (committed)

All synthetic, template-based, generated by arouse/agent/synth.py. Deterministic per seed.
AgentBench v1 (benchmarks/agentbench_v1, seeds 9001/777) was made by the v1-v3 generator and is kept frozen;
the current generator writes AgentBench v2 (seeds 9002/778), which adds questions, GST and leads.
Usage: python scripts/build_agent_data.py [--name agent_v4] [--train 120000] [--bench]
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from arouse.agent.episode import render_text
from arouse.agent.synth import episode_header, generate

TRAIN_SEED, TEST_SEED, INDIST_SEED = 104, 9002, 778


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def write_jsonl(path: Path, rows) -> int:  # noqa: ANN001
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
            n += 1
    return n


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--train", type=int, default=120000)
    ap.add_argument("--test", type=int, default=480)
    ap.add_argument("--indist", type=int, default=180)
    ap.add_argument("--name", default="agent_v4")
    ap.add_argument("--bench-dir", default="benchmarks/agentbench_v2")
    ap.add_argument("--bench", action="store_true", help="also (re)write <bench-dir>/*.jsonl")
    a = ap.parse_args()
    a.out = f"artifacts/datasets/{a.name}"

    out = Path(a.out)
    train_path = out / "train.jsonl"
    write_jsonl(train_path, ({"text": render_text(episode_header(e), e["events"])} for e in generate(a.train, TRAIN_SEED, "train")))
    bench = Path(a.bench_dir)
    if a.bench:  # off by default: the benchmark stays fixed so results remain comparable across data versions
        write_jsonl(bench / "test.jsonl", generate(a.test, TEST_SEED, "test"))
        write_jsonl(bench / "in_distribution.jsonl", generate(a.indist, INDIST_SEED, "train"))

    manifest = {
        "dataset": a.name,
        "external_sources": [],
        "files": [
            {"file": str(train_path), "episodes": a.train, "sha256": sha256(train_path),
             "origin": f"arouse/agent/synth.py split=train seed={TRAIN_SEED}", "license": "project-owned"},
            {"file": str(bench / "test.jsonl"), "episodes": a.test, "sha256": sha256(bench / "test.jsonl"),
             "origin": f"arouse/agent/synth.py split=test seed={TEST_SEED} (held-out tasks, facts, files, templates)",
             "license": "project-owned"},
            {"file": str(bench / "in_distribution.jsonl"), "episodes": a.indist, "sha256": sha256(bench / "in_distribution.jsonl"),
             "origin": f"arouse/agent/synth.py split=train seed={INDIST_SEED}", "license": "project-owned"},
        ],
    }
    Path(f"datasets/{a.name}").mkdir(parents=True, exist_ok=True)
    Path(f"datasets/{a.name}/MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
