#!/usr/bin/env python3
"""Build the Arouse agent corpus (v1) and the AgentBench v1 case files.

    artifacts/datasets/agent_v1/train.jsonl        {"text": rendered episode}  (large, not committed)
    datasets/agent_v1/MANIFEST.json                provenance + sha256 (committed)
    benchmarks/agentbench_v1/test.jsonl            held-out tasks/templates (committed)
    benchmarks/agentbench_v1/in_distribution.jsonl train-distribution samples, unseen seeds (committed)

All synthetic, template-based, generated by arouse/agent/synth.py. Deterministic per seed.
Usage: python scripts/build_agent_data.py [--train 60000] [--test 400] [--indist 150]
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from arouse.agent.episode import render_text
from arouse.agent.synth import episode_header, generate

TRAIN_SEED, TEST_SEED, INDIST_SEED = 101, 9001, 777


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def write_jsonl(path: Path, rows) -> int:  # noqa: ANN001
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
            n += 1
    return n


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--train", type=int, default=60000)
    ap.add_argument("--test", type=int, default=400)
    ap.add_argument("--indist", type=int, default=150)
    ap.add_argument("--out", default="artifacts/datasets/agent_v1")
    a = ap.parse_args()

    out = Path(a.out)
    train_path = out / "train.jsonl"
    write_jsonl(train_path, ({"text": render_text(episode_header(e), e["events"])} for e in generate(a.train, TRAIN_SEED, "train")))
    bench = Path("benchmarks/agentbench_v1")
    write_jsonl(bench / "test.jsonl", generate(a.test, TEST_SEED, "test"))
    write_jsonl(bench / "in_distribution.jsonl", generate(a.indist, INDIST_SEED, "train"))

    manifest = {
        "dataset": "agent_v1",
        "external_sources": [],
        "files": [
            {"file": str(train_path), "episodes": a.train, "sha256": sha256(train_path),
             "origin": f"arouse/agent/synth.py split=train seed={TRAIN_SEED}", "license": "project-owned"},
            {"file": str(bench / "test.jsonl"), "episodes": a.test, "sha256": sha256(bench / "test.jsonl"),
             "origin": f"arouse/agent/synth.py split=test seed={TEST_SEED} (held-out tasks, facts, files, templates)",
             "license": "project-owned"},
            {"file": str(bench / "in_distribution.jsonl"), "episodes": a.indist, "sha256": sha256(bench / "in_distribution.jsonl"),
             "origin": f"arouse/agent/synth.py split=train seed={INDIST_SEED}", "license": "project-owned"},
        ],
    }
    Path("datasets/agent_v1").mkdir(parents=True, exist_ok=True)
    Path("datasets/agent_v1/MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
