#!/usr/bin/env python3
"""Run a fixed conversation through a trained Arouse model + sandbox and write the REAL
outputs to a Markdown transcript (nothing is edited or cherry-picked).

Usage: python scripts/demo_transcript.py --model checkpoints/arouse-agent-s --out docs/demo_transcript.md
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

from arouse.agent.context import build_context
from arouse.agent.episode import Header
from arouse.agent.runtime import AgentRuntime
from arouse.agent.tools import REGISTRY, Sandbox
from arouse.agent.business import sample_customers
from arouse.api.agent_service import DEMO_FILES
from arouse.inference import InferenceEngine

NOW = datetime(2026, 9, 30, 19, 21)  # fixed clock so the transcript is reproducible (a Wednesday)
CONVERSATION = [
    "hello",
    "Remind me tomorrow at 8 AM to check sales.",
    "Every Monday at 9 AM remind me to pay the staff.",
    "Remind me tomorrow to call the vet.",
    "7:30 pm",
    "In 2 hours remind me to feed the calves.",
    "What reminders do I have?",
    "Cancel my reminder to check sales.",
    "Note that the feed delivery is late.",
    "How many lines are in sales.csv?",
    "Read invoices.csv",
    "Remind me today at 7 AM to water the plants.",
    "yes",
    "Remind me on Friday to order feed.",
    "6 pm",
    "Please jot down: the market is closed on Sunday.",
    "Delete my reminder to order spare pump parts.",
    "What is the capital of France?",
    "What is the GST on gold?",
    "Calculate GST on 2.5 lakh at 3%.",
    "How much GST on 1180?",
    "18%",
    "Find me leads",
    "2",
    "Find me more leads",
    "none of these",
    "customers in Pune who like gold",
    "thanks",
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--out", default="docs/demo_transcript.md")
    a = ap.parse_args()
    engine = InferenceEngine.from_pretrained(a.model)
    info = engine.info()
    rt = AgentRuntime(engine, REGISTRY)
    sb = Sandbox(NOW, {**DEMO_FILES, "customers.csv": sample_customers(NOW)})
    header = Header(context=build_context(NOW, "Asia/Kolkata"), tools=REGISTRY.names())
    events: list[dict] = []
    lines = [
        "# Demo transcript (real model output)",
        "",
        f"Model `{info['name']}`: {info['num_parameters']:,} params. {engine.meta.get('notes', '')} "
        f"Clock fixed at {NOW:%Y-%m-%d %H:%M} ({NOW:%A}). Generated by `scripts/demo_transcript.py`; nothing edited.",
        "",
    ]
    for msg in CONVERSATION:
        events.append({"type": "user", "content": msg})
        res = rt.run(header, events, sb.execute)
        events.extend(res.events)
        lines.append(f"**User:** {msg}  ")
        for ev in res.events:
            if ev["type"] == "arouse" and ev["turn"]["action"]["type"] == "tool_call":
                act = ev["turn"]["action"]
                lines.append(f"&nbsp;&nbsp;↳ `{act['tool']} {json.dumps(act['arguments'])}`  ")
            elif ev["type"] in ("tool_result", "tool_error"):
                lines.append(f"&nbsp;&nbsp;↳ {ev['type']}: `{json.dumps(ev['content'])[:150]}`  ")
        f = res.final
        tag = {"finish": "", "ask_user": " *(question)*", "fail": " *(failed)*"}[f.type]
        guard = " *(guard)*" if any(t.guarded for t in res.turns) else ""
        lines.append(f"**Arouse:** {f.result or f.question or f.error}{tag}{guard}")
        lines.append("")
    lines += ["Final sandbox state:", "", "```json", json.dumps(sb.snapshot(), indent=2), "```", ""]
    Path(a.out).write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
